### PR TITLE
Rendering and TOC support when working with Readium 2 WebPub

### PR DESCRIPTION
**Pull request by barbender**
### Additional information
See README.md branch specific description.

### CODE REVIEW

**Comment by danielweck** [comment]
That's great thank you, but IMO we absolutely need to try to cleanup the `js/epub-model/package_document_parser.js` code diff, as right now it is very hard to decipher. I think it is because of source formatting.

**Comment by danielweck** [comment]
Regarding the confusing code diff, I think it comes from this commit: https://github.com/readium/readium-js/pull/179/commits/70f8c59d63baf8ebecad8084a1da2e664cb892f8#diff-a0f4cfa7d42ecf666a546180eb1a82aa

**Comment by danielweck** [comment]
I created a separate branch just to test your code, with a clean patch:
https://github.com/readium/readium-js/compare/feature/readium2...feature/readium2-evidentpoint
(as you can see, the `js/epub-model/package_document_parser.js` source diff is now legible)

I will delete this temporary branch `feature/readium2-evidentpoint` of course, we will merge your PR. But could you please try to reduce the code diff? (rollback source formatting in unchanged parts?)

**Comment by danielweck** [comment]
I deployed your code (from my patched branch) on this server:

**childrens-literature.epub**
http://readium-2.surge.sh/?epub=https%3A%2F%2Freadium2.herokuapp.com%2Fpub%2FL2FwcC9jaGlsZHJlbnMtbGl0ZXJhdHVyZS5lcHVi%2Fmanifest.json

**wasteland-otf-obf.epub**
http://readium-2.surge.sh/?epub=https%3A%2F%2Freadium2.herokuapp.com%2Fpub%2FL2FwcC93YXN0ZWxhbmQtb3RmLW9iZi5lcHVi%2Fmanifest.json

Note that there is something wrong with obfuscated fonts in Wasteland (above link). The fonts are de-obfuscated on the server (see https://readium2.herokuapp.com/pub/L2FwcC93YXN0ZWxhbmQtb3RmLW9iZi5lcHVi/EPUB/wasteland-content.xhtml ), yet they are not rendered correctly in the cloud reader. I suspect that your code is attempting to de-obfuscate them twice? I will check.

**Comment by danielweck** [comment]
Regarding obfuscated fonts: no, the problem is somewhere else. Not sure what is going on in the web browser, as the CSS and font faces are loaded correctly. Tested on Safari and Chrome OSX.

**Comment by danielweck** [comment]
Obfuscated fonts work on Firefox on OSX, so I guess there's something wrong with Safari and Chrome...never mind.

**Comment by JCCR** [comment]
@danielweck 
Obf fonts seem to work for me (fresh Chrome profile)
screen shot 2017-05-31 at 3 00 17 pm

**Comment by barbender** [comment]
Hi Daniel,
Sorry for the confusion due to formatting changes in `js/epub-model/package_document_parser.js`
Now that you fixed the formatting in feature/readium2-evidentpoint, do you want us to continue development in this branch? Or going back to feature/readium2?
regards, Michael

**Comment by danielweck** [comment]
Thanks Juan. Safari version 10.1.1 (11603.2.5) here. Chrome version 58.0.3029.110. Caching disabled. 64-bit OSX (El Capitan 10.11.6)

**Comment by danielweck** [comment]
@barbender it would be preferable to preserve your git commit history, and therefore to cleanup your branch code diffs. What do you think?

**Comment by barbender** [comment]
@danielweck makes sense, I have just updated the pull request.

**Pull request merged**
