### PR TITLE
Fallback solution for browsers not handling Blobs

### PR DESCRIPTION
**Pull request by johanpoirier**
This is a revival of #73 

We're using the [bowser](https://github.com/lancedikson/bowser) lib to detect which browser is used. Then we choose the method for loading iframes since IE, old Safari and Samsung Internet are not handling Blob URLs correctly.

#### Related issue(s) and/or pull request(s)
#72 and #73 and more recent https://github.com/readium/readium-js-viewer/issues/702

#### Test cases, sample files
@danielweck how do we set up the readium-js-viewer on a test page for testing that PR?

### CODE REVIEW

**Comment by johanpoirier** [comment]
I tested it on the Samsung Internet Browser version 6.4.10.5 on my Moto G5S Plus (android 7.1.1).

**Comment by danielweck** [comment]
This looks great, thank you! I have re-targeted the PR from `master` to `develop`.

**Comment by danielweck** [comment]
I closed the old PR: https://github.com/readium/readium-js/pull/73

**Comment by danielweck** [comment]
I fixed the Git conflict in ` build-config/RequireJS_config_common.js`. Merging. I will check the NPM `package-lock.json` as I am doing a pass on dependencies anyway.

**Comment by danielweck** [comment]
Follow-up specific to Chrome on iOS: https://github.com/readium/readium-js/commit/a5684d8a5c1e8a32721efd2fc458d6ffa9b7edd3

**Pull request merged**
