### PR TITLE
Fix incorrect dom tree produced in IE11 when source has self-closed tags

### PR DESCRIPTION
**Pull request by kimtuck**
### Additional information
Because of the way that the document is loaded into the iframe for IE, self-closing tags can lead to an incorrect DOM tree.  This code replaces self-closed tags with non-self-closing tags, which eliminates the problem.

### CODE REVIEW

**Comment by danielweck** [comment]
I think this should be an additional pre-processing step in:
https://github.com/readium/readium-js/blob/develop/js/Readium.js#L27
```javascript
var _contentDocumentTextPreprocessor = function(src, contentDocumentHtml) {
...
```

https://github.com/readium/readium-js/blob/develop/js/epub-fetch/iframe_zip_loader.js#L291
```javascript
   contentDocumentHtml = _contentDocumentTextPreprocessor(src, contentDocumentHtml);
```

**Comment by danielweck** [comment]
@matwood already proposed a generic "self-closing" tag replacement routine:
https://github.com/readium/readium-js/pull/136/files#diff-d45cdc8100690ade3fbd3b563a26b51bL66

...so I am closing this PR.
Thanks @kimtuck ! :)

**Comment by johanpoirier** [comment]
Why this PR has never been merge https://github.com/readium/readium-js/pull/87 ?

**Comment by danielweck** [comment]
Good reminder @johanpoirier 
I think `content_document_fetcher.js` is only used in the case of "programmatic fetching" (zipped EPUBs and exploded EPUBs with obfuscated fonts), whereas the `contentDocumentTextPreprocessor()` design applies to regular exploded EPUBs as well.

**Comment by kimtuck** [comment]
OK, thanks.

**Pull request closed without merging**
